# Site settings
title:          "Marco Ciccone"
description:    "Academic website"
baseurl:        "/"
url:            "https://marcociccone.github.io"

# Author
author:
  name:         Marco Ciccone
  url:          https://marcociccone.github.io
  email:        marco.ciccone@polito.it
  github:       marcociccone
  twitter:      mciccone_AI
  linkedin:     cicconemarco
  scholar:      hOQjblcAAAAJ
  me:           ciccone

# Analytics
analytics:
  provider               : google
  google:
    tracking_id          : 

contact_note: If you want to discuss about research ideas and opportunities, please drop me an email

# Comments
disqus_shortname: # put your disqus shortname

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  math_engine: mathjax
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  sass_dir: _sass
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  #  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

whitelist:
  - jekyll-redirect-from

# Includes
include: ['_pages']

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt

enable_anchorjs:    false
enable_katex:       false
